name: datastream-ops

on:
  workflow_dispatch:
    inputs:
      operation:
        description: "pause | resume | restart"
        required: true
        default: "restart"
      stream_id:
        description: "Datastream Stream ID (example: dev-medina-p1-append)"
        required: true
      location:
        description: "Datastream location (example: europe-west2)"
        required: true
        default: "europe-west2"

permissions:
  contents: read
  id-token: write

jobs:
  ops:
    runs-on: ubuntu-latest
    steps:
      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.TF_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Execute operation
        env:
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          LOCATION: ${{ github.event.inputs.location }}
          STREAM_ID: ${{ github.event.inputs.stream_id }}
          OP: ${{ github.event.inputs.operation }}
        run: |
          set -euo pipefail

          echo "Operation: ${OP}"
          echo "Stream: ${STREAM_ID}"
          echo "Location: ${LOCATION}"
          echo "Project: ${PROJECT_ID}"

          if [[ "${OP}" == "pause" ]]; then
            gcloud datastream streams pause "${STREAM_ID}" --project="${PROJECT_ID}" --location="${LOCATION}"
          elif [[ "${OP}" == "resume" ]]; then
            gcloud datastream streams resume "${STREAM_ID}" --project="${PROJECT_ID}" --location="${LOCATION}"
          elif [[ "${OP}" == "restart" ]]; then
            gcloud datastream streams pause "${STREAM_ID}" --project="${PROJECT_ID}" --location="${LOCATION}" || true 
            echo "Waiting 10 minutes before resuming..."
            sleep 600
            echo "Resuming stream..."  redo
#          if hard restart required we have to use that one - later
            gcloud datastream streams resume "${STREAM_ID}" --project="${PROJECT_ID}" --location="${LOCATION}"
          else
            echo "Invalid operation: ${OP}. Expected pause | resume | restart"
            exit 1
          fi

      - name: Describe stream (post-check)
        env:
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          LOCATION: ${{ github.event.inputs.location }}
          STREAM_ID: ${{ github.event.inputs.stream_id }}
        run: |
          gcloud datastream streams describe "${STREAM_ID}" --project="${PROJECT_ID}" --location="${LOCATION}" || true
