name: terraform-plan

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-*.yml"

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.TF_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="prefix=datastream/dev"

      - name: Terraform Validate
        working-directory: terraform/envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        run: terraform plan -var-file="dev.tfvars"
